name = "ckds-website"
compatibility_date = "2024-11-20"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ckds-database"
database_id = "d9835972-bdfe-4fdc-b61a-3b0a606ecad6"
